[package]
name = "new_king"
version = "0.1.0"
authors = ["Jan-Piotraschke <piotraschke.janniklas@gmail.com>"]
edition = "2021"

[lib]
name = "new_king_lib"
path = "src/lib.rs"
# crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.84"
autocxx = "0.26.0"
cxx = "1.0.110"
miette = "5.10.0"
tch = "0.14.0"
plotters = "0.3.5"

[build-dependencies]
autocxx-build = "0.26.0"
miette = { version = "5", features = ["fancy"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
